### ISSUE TITLE
Crash on empty DownloadUrls in the config.yaml

### ISSUE THREAD

**Issue by oldshensheep** [zu1k/nali#161]
After upgrade to 0.7.2, nali will crash if previous `config.yaml` not exits `download-urls` in the section of `qqwry`.
E.g.
```
    - name: qqwry
      name-alias:
        - chunzhen
      format: qqwry
      file: qqwry.dat
      languages:
        - zh-CN
      types:
        - IPv4
```

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/zu1k/nali/internal/migration.migration2v7()
        github.com/zu1k/nali/internal/migration/v7.go:32 +0x3a9
github.com/zu1k/nali/internal/migration.init.0()
        github.com/zu1k/nali/internal/migration/mirgration.go:5 +0x1c
```
